#!/bin/bash

WRAPPER="`readlink -f "$0"`"

HERE="`dirname $WRAPPER"`"

if [[ -n "$LD_LIBRARY_PATH" ]]; then
  LD_LIBRARY_PATH="$HERE/../lib:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="$HERE/../lib"
fi

export LD_LIBRARY_PATH

exec -a "$0" "$HERE/cliver-bin" "$@"

