#!/bin/bash

WRAPPER="`readlink -f "$0"`"

HERE="`dirname $WRAPPER"`"

EXTRA_LIBS="$HERE/../lib:$HERE/../../local/lib"

if [[ -n "$LD_LIBRARY_PATH" ]]; then
  LD_LIBRARY_PATH="$EXTRA_LIBS:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="$EXTRA_LIBS"
fi

export LD_LIBRARY_PATH

exec -a "$0" "$HERE/cliver-bin" "$@"

