#===-- klee/Makefile.rules - Common make rules for KLEE ----*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#
#
#===------------------------------------------------------------------------===#

ifeq ($(ENABLE_PROFILING),1)
  ifeq ($(DISABLE_GOOGLE_PROFILING),1)
  else
    CXX.Flags := $(filter-out -pg -g,$(CXX.Flags))
    C.Flags   := $(filter-out -pg -g,$(C.Flags))
    LD.Flags  := $(filter-out -pg -g,$(LD.Flags)) -lprofiler
    CPP.Defines += -DGOOGLE_PROFILER 
  endif
endif

ifeq ($(DISABLE_TCMALLOC),1)
else
  CXX.Flags += -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free
  LD.Flags += -ltcmalloc
endif


