#===-- klee/Makefile.rules - Common make rules for KLEE ----*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

ifeq ($(ENABLE_GOOGLE_PROFILING),1)
  BuildMode := $(BuildMode)+GProfile
  CXX.Flags := $(filter-out -fomit-frame-pointer,$(CXX.Flags))
  C.Flags   := $(filter-out -fomit-frame-pointer,$(C.Flags))
  LD.Flags  := $(filter-out -fomit-frame-pointer,$(LD.Flags))
  KEEP_SYMBOLS := 1
  CPP.Defines += -DGOOGLE_PROFILER 
  LD.Flags += -lprofiler 
endif

ifeq ($(DISABLE_TCMALLOC),1)
  BuildMode := $(BuildMode)-TCMalloc
else
  CXX.Flags += -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free
  LD.Flags += -ltcmalloc
endif


