// REQUIRES: not-llvm-3.4
// RUN: %klee -cliver -posix-runtime -libc=uclibc -client-model=tetrinet -socket-log "%S/game_0_0_1_1_10_p1_localhost.ktest" -no-output "%S/tetrinet.bc" -autostart -startingheight 0 -partialtype 1 -partialrate 1 -inputgenerationtype 64 -maxround 10 -seed 0 p1 localhost &> %t_cliver.log
// RUN: grep -q "Verification complete" %t_cliver.log
// RUN: mkdir -p %t_training.cliver.dir
// RUN: %klee -cliver -posix-runtime -libc=uclibc -cliver-mode=training -client-model=tetrinet -socket-log "%S/game_0_0_1_1_10_p1_localhost.ktest" -output-dir-parent "%t_training.cliver.dir" "%S/tetrinet.bc" -autostart -startingheight 0 -partialtype 1 -partialrate 1 -inputgenerationtype 64 -maxround 10 -seed 0 p1 localhost &> %t_training.cliver.log
// RUN: grep -q "Verification complete" %t_training.cliver.log
// RUN: %klee -use-threads=1 -cliver -posix-runtime -libc=uclibc -use-clustering -cliver-mode=edit-dist-kprefix-row -client-model=tetrinet -use-self-training -socket-log "%S/game_0_0_1_1_10_p1_localhost.ktest" -self-training-path-dir="%t_training.cliver.dir/cliver-last" -no-output "%S/tetrinet.bc" -autostart -startingheight 0 -partialtype 1 -partialrate 1 -inputgenerationtype 64 -maxround 10 -seed 0 p1 localhost &> %t_self.cliver.log
// RUN: grep -q "Verification complete" %t_self.cliver.log
// RUN: not grep -q "Self Training Data Mismatch" %t_self.cliver.log
// RUN: %klee -cliver -posix-runtime -libc=uclibc -use-clustering -cliver-mode=edit-dist-kprefix-row -client-model=tetrinet -socket-log "%S/game_0_0_1_1_10_p1_localhost.ktest" -no-output "%S/tetrinet.bc" -autostart -startingheight 0 -partialtype 1 -partialrate 1 -inputgenerationtype 64 -maxround 10 -seed 0 p1 localhost &> %t_editdist.cliver.log
// RUN: grep -q "Verification complete" %t_editdist.cliver.log
