// RUN: rm -rf %t_training.cliver-out
// RUN: %klee %xpilotcliverparams -cliver-mode=training -socket-log "%S/xpilot_0.ktest" -output-dir="%t_training.cliver-out" "%S/%xpilotbc" %xpilotparams &> %t.log
// RUN: grep -q "Verification complete" %t.log
// RUN: rm -rf %t.cliver-out
// RUN: %klee %xpilotcliverparams -output-dir=%t.cliver-out -use-clustering -cliver-mode=jaccard -socket-log "%S/xpilot_0.ktest" -training-path-dir="%t_training.cliver-out" "%S/%xpilotbc" %xpilotparams &> %t.ed.log
// RUN: grep -q "Verification complete" %t.ed.log
// REQUIRES: threads
