// REQUIRES: llvm-3.4
// RUN: rm -rf %t_training.cliver-out
// RUN: %klee %xpilotcliverparams -cliver-mode=training -socket-log "%S/xpilot_0.ktest" -output-dir="%t_training.cliver-out" "%S/xpilot.bc" %xpilotparams &> %t.log
// RUN: grep -q "Verification complete" %t.log
// RUN: rm -rf %t.cliver-out
// RUN: %klee %xpilotcliverparams -output-dir=%t.cliver-out -use-clustering -cliver-mode=edit-dist-kprefix-row -use-self-training -socket-log "%S/xpilot_0.ktest" -self-training-path-dir="%t_training.cliver-out" "%S/xpilot.bc" %xpilotparams &> %t.ed.log
// RUN: grep -q "Verification complete" %t.ed.log
// RUN: not grep -q "Self Training Data Mismatch" %t.ed.log
