// REQUIRES: llvm-3.4
// RUN: %klee -cliver -posix-runtime -libc=uclibc -client-model=xpilot -load="libX11.so" -no-xwindows -socket-log "%S/xpilot_0.ktest" -no-output "%S/xpilot.bc" -join -texturedWalls no -texturedDecor no -texturedObjects no  -fullColor no -geometry 800x600+100+100 -keyTurnLeft a -keyTurnRight d -keyThrust w localhost &> %t_cliver.log
// RUN: grep -q "Verification complete" %t_cliver.log
// RUN: mkdir -p %t_training.cliver.dir
// RUN: %klee -cliver -posix-runtime -libc=uclibc -cliver-mode=training -client-model=xpilot -load="libX11.so" -no-xwindows -socket-log "%S/xpilot_0.ktest" -output-dir-parent "%t_training.cliver.dir" "%S/xpilot.bc" -join -texturedWalls no -texturedDecor no -texturedObjects no -fullColor no -geometry 800x600+100+100 -keyTurnLeft a -keyTurnRight d -keyThrust w localhost &> %t_training.cliver.log
// RUN: grep -q "Verification complete" %t_training.cliver.log
// RUN: %klee -cliver -use-threads=1 -posix-runtime -libc=uclibc -use-clustering -cliver-mode=edit-dist-kprefix-row -client-model=xpilot -load="libX11.so" -no-xwindows -use-self-training -socket-log "%S/xpilot_0.ktest" -self-training-path-dir="%t_training.cliver.dir/cliver-last" -no-output "%S/xpilot.bc" -join -texturedWalls no -texturedDecor no -texturedObjects no -fullColor no -geometry 800x600+100+100 -keyTurnLeft a -keyTurnRight d -keyThrust w localhost &> %t_self.cliver.log
// RUN: grep -q "Verification complete" %t_self.cliver.log
// RUN: %klee -cliver -posix-runtime -libc=uclibc -use-clustering -cliver-mode=edit-dist-kprefix-row -client-model=xpilot -load="libX11.so" -no-xwindows -socket-log "%S/xpilot_0.ktest" -no-output "%S/xpilot.bc" -join -texturedWalls no -texturedDecor no -texturedObjects no -fullColor no -geometry 800x600+100+100 -keyTurnLeft a -keyTurnRight d -keyThrust w localhost &> %t_editdist.cliver.log
// RUN: grep -q "Verification complete" %t_editdist.cliver.log
// RUN: not grep -q "Self Training Data Mismatch" %t_self.cliver.log
