#===-- lib/Passes/Makefile ---------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=../../..

LIBRARYNAME=kleePasses
LOADABLE_MODULE = 1

include $(LEVEL)/Makefile.common
